version: '3.8'

services:
  kaban-app:
    build: .
    image: demensdeum/kaban-board:latest
    container_name: kaban-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
